# Generated by Django 4.1.1 on 2022-09-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("subtitle", models.CharField(max_length=300)),
                (
                    "books",
                    models.ManyToManyField(related_name="books", to="books.book"),
                ),
            ],
        ),
    ]
