# Generated by Django 4.1.1 on 2022-09-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_alter_book_user"),
        ("rooms", "0002_room_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="books",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="books.book"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
