# Generated by Django 4.1.1 on 2022-09-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_user"),
        ("rooms", "0003_alter_room_books_alter_room_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="books",
            field=models.ManyToManyField(blank=True, to="books.book"),
        ),
    ]
